export default {
  login: 'fuadhasan08',
  id: 68866471,
  node_id: 'MDQ6VXNlcjY4ODY2NDcx',
  avatar_url: 'https://avatars.githubusercontent.com/u/68866471?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/fuadhasan08',
  html_url: 'https://github.com/fuadhasan08',
  followers_url: 'https://api.github.com/users/fuadhasan08/followers',
  following_url:
    'https://api.github.com/users/fuadhasan08/following{/other_user}',
  gists_url: 'https://api.github.com/users/fuadhasan08/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/fuadhasan08/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/fuadhasan08/subscriptions',
  organizations_url: 'https://api.github.com/users/fuadhasan08/orgs',
  repos_url: 'https://api.github.com/users/fuadhasan08/repos',
  events_url: 'https://api.github.com/users/fuadhasan08/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/fuadhasan08/received_events',
  type: 'User',
  site_admin: false,
  name: 'Fuad Hasan',
  company: null,
  blog: '',
  location: 'Ishwarganj, Mymensingh',
  email: null,
  hireable: null,
  bio: 'Love to code',
  twitter_username: null,
  public_repos: 28,
  public_gists: 0,
  followers: 1,
  following: 5,
  created_at: '2020-07-27T16:50:19Z',
  updated_at: '2022-12-14T18:32:38Z',
}
